#!/usr/bin/env bash


# Generate SSH key
if [ ! -f ~/.ssh/id_rsa.pub ]; then
  ssh-keygen -t rsa -C "stevenyung@icloud.com" -b 4096
fi


# Pull dotfiles repository
mkdir ~/Code
git clone https://github.com/stvnyung/dotfiles ~/Code/dotfiles

# Install Homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew doctor
brew update
