#!/usr/bin/env bash

# Pull dotfiles repository
mkdir ~/Code
git clone https://github.com/stvnyung/dotfiles ~/Code/dotfiles

# Install Homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew doctor
brew update
