#!/usr/bin/env bash

# Oh My Zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
chsh -s $(which zsh)
ln -fs ~/Code/dotfiles/zshrc.symlink ~/.zshrc

# Javascript
brew install node
brew install yarn

# Dev
brew install tig
brew install mysql

# Visual Studio Code
brew cask install visual-studio-code
code --install-extension ms-vscode.atom-keybindings
code --install-extension eamodio.gitlens
code --install-extension vscodevim.vim
code --install-extension azemoh.one-monokai
ln -fs ~/Code/dotfiles/settings.json ~/Library/Application\ Support/Code/User/
ln -fs ~/Code/dotfiles/keybindings.json ~/Library/Application\ Support/Code/User/
ln -fs ~/Code/dotfiles/snippets ~/Library/Application\ Support/Code/User/

# General
brew cask install slack
brew cask install firefox
brew cask install spotify
brew cask install google-chrome
brew cask install avast-security
brew cask install brave-browser

# Install App Store apps
# brew install mas
# mas signin stevenyung@icloud.com
# mas install 1278508951 # Trello
# mas install 409203825 # Numbers
# mas install 973134470 # Be Focused (Pomodoro timer)

# Setup MacOS Dock
defaults write com.apple.dock static-only -bool TRUE # Only show active apps
defaults write com.apple.dock autohide-time-modifier -int 0 # Remove Dock hide / show animation
defaults write com.apple.dock autohide -bool true # Enable Dock auto-hide
killall Dock # Reset Dock
open https://goo.gl/6fMg2D # Redirect to a link enable switch between windows

# Setup git
git config --global user.name "Steven Yung"
git config --global user.email stevenyung@icloud.com
git config --global core.editor vi # Setup vi as default editor
