#!/usr/bin/env bash

# Oh My Zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
if [ ! -f .first ]; then
    chsh -s $(which zsh)
    ln -fs ~/Code/dotfiles/zshrc.symlink ~/.zshrc
fi

# PHP
brew install homebrew/php/composer
# Valet
composer global require laravel/valet
valet install
valet park ~/Code

# Javascript
brew install node
brew install yarn

# Dev
brew install tig
brew install tldr
brew install mysql
brew cask install sequel-pro
brew cask install visual-studio-code

# General
brew cask install flux
brew cask install slack
brew cask install firefox
brew cask install spotify
brew cask install evernote
brew cask install google-chrome
brew cask install avast-security

# Install App Store apps
brew install mas
mas signin stevenyung@icloud.com
mas install 1278508951 # Trello

if [ ! -f .first ]; then
    # Setup MacOS Dock
    defaults write com.apple.dock static-only -bool TRUE # Only show active apps
    defaults write com.apple.dock autohide-time-modifier -int 0 # Remove Dock hide / show animation
    defaults write com.apple.dock autohide -bool true # Enable Dock auto-hide
    killall Dock # Reset Dock
    open https://goo.gl/6fMg2D # Redirect to a link enable switch between windows
fi

if [ ! -f .first ]; then
    # Setup git
    git config --global user.name "Steven Yung"
    git config --global user.email stevenyung@icloud.com
    git config --global core.editor vi # Setup vi as default editor
fi

# Upgrade
brew upgrade
brew cask upgrade
mas upgrade

# Generate SSH key
if [ ! -f ~/.ssh/id_rsa.pub ]; then
    ssh-keygen -t rsa -C "stevenyung@icloud.com" -b 4096
fi

# Create a empty file which will serve a token to indicate that the setup already happened once
if [ ! -f .first ]; then
    touch .first
fi