#!/usr/bin/env php
<?php

require_once(__DIR__ . '/../vendor/autoload.php');

use Symfony\Component\Console\Application;
use Dotfiles\Commands\SetupCommand;

$app = new Application;

$app->add(new SetupCommand);

$app->run();
