#!/bin/bash

# PHP 5.4
source ~/Code/dotfiles/php/unlink.sh
brew link php54
brew install homebrew/php/php54-apc
brew install homebrew/php/php54-apcu
brew install homebrew/php/php54-augmentedtypes
brew install homebrew/php/php54-binpack
brew install homebrew/php/php54-blitz
brew install homebrew/php/php54-boxwood
brew install homebrew/php/php54-chdb
brew install homebrew/php/php54-crypto
brew install homebrew/php/php54-dbase
brew install homebrew/php/php54-dbus
brew install homebrew/php/php54-eio
brew install homebrew/php/php54-ev
brew install homebrew/php/php54-fast_assert
brew install homebrew/php/php54-gearman
brew install homebrew/php/php54-geoip
brew install homebrew/php/php54-gmagick
brew install homebrew/php/php54-gmp
brew install homebrew/php/php54-gnupg
brew install homebrew/php/php54-graphdat
brew install homebrew/php/php54-hprose
brew install homebrew/php/php54-htscanner
brew install homebrew/php/php54-httpparser
brew install homebrew/php/php54-jsmin
brew install homebrew/php/php54-kafka
brew install homebrew/php/php54-leveldb
brew install homebrew/php/php54-libevent
brew install homebrew/php/php54-libsodium
brew install homebrew/php/php54-libvirt
brew install homebrew/php/php54-lz4

# PHP 5.5
source ~/Code/dotfiles/php/unlink.sh
brew link php55
brew install homebrew/php/php55-apcu
brew install homebrew/php/php55-augmentedtypes
brew install homebrew/php/php55-binpack
brew install homebrew/php/php55-blitz
brew install homebrew/php/php55-boxwood
brew install homebrew/php/php55-chdb
brew install homebrew/php/php55-crypto
brew install homebrew/php/php55-dbase
brew install homebrew/php/php55-dbus
brew install homebrew/php/php55-eio
brew install homebrew/php/php55-ev
brew install homebrew/php/php55-fast_assert
brew install homebrew/php/php55-gearman
brew install homebrew/php/php55-geoip
brew install homebrew/php/php55-gmagick
brew install homebrew/php/php55-gmp
brew install homebrew/php/php55-gnupg
brew install homebrew/php/php55-graphdat
brew install homebrew/php/php55-hprose
brew install homebrew/php/php55-htscanner
brew install homebrew/php/php55-httpparser
brew install homebrew/php/php55-jsmin
brew install homebrew/php/php55-kafka
brew install homebrew/php/php55-leveldb
brew install homebrew/php/php55-libevent
brew install homebrew/php/php55-libsodium
brew install homebrew/php/php55-libvirt
brew install homebrew/php/php55-lz4
brew install homebrew/php/php55-lzf

# PHP 5.6
source ~/Code/dotfiles/php/unlink.sh
brew link php56
brew install homebrew/php/php56-apcu
brew install homebrew/php/php56-augmentedtypes
brew install homebrew/php/php56-binpack
brew install homebrew/php/php56-blitz
brew install homebrew/php/php56-boxwood
brew install homebrew/php/php56-chdb
brew install homebrew/php/php56-crypto
brew install homebrew/php/php56-dbase
brew install homebrew/php/php56-dbus
brew install homebrew/php/php56-eio
brew install homebrew/php/php56-ev
brew install homebrew/php/php56-fast_assert
brew install homebrew/php/php56-gearman
brew install homebrew/php/php56-geoip
brew install homebrew/php/php56-gmagick
brew install homebrew/php/php56-gnupg
brew install homebrew/php/php56-graphdat
brew install homebrew/php/php56-hprose
brew install homebrew/php/php56-htscanner
brew install homebrew/php/php56-httpparser
brew install homebrew/php/php56-jsmin
brew install homebrew/php/php56-kafka
brew install homebrew/php/php56-leveldb
brew install homebrew/php/php56-libevent
brew install homebrew/php/php56-libsodium
brew install homebrew/php/php56-libvirt
brew install homebrew/php/php56-lz4
brew install homebrew/php/php56-lzf
brew install homebrew/php/php56-mailparse

# PHP 7.0
source ~/Code/dotfiles/php/unlink.sh
brew link php70
brew install homebrew/php/php70-blitz
brew install homebrew/php/php70-ds
brew install homebrew/php/php70-ev
brew install homebrew/php/php70-geoip
brew install homebrew/php/php70-gmagick
brew install homebrew/php/php70-hprose
brew install homebrew/php/php70-kafka
brew install homebrew/php/php70-libsodium
brew install homebrew/php/php70-lz4
brew install homebrew/php/php70-lzf
brew install homebrew/php/php70-mailparse
brew install homebrew/php/php70-maxminddb
brew install homebrew/php/php70-mecab
brew install homebrew/php/php70-oauth
brew install homebrew/php/php70-ref
brew install homebrew/php/php70-scrypt
brew install homebrew/php/php70-solr
brew install homebrew/php/php70-stats
brew install homebrew/php/php70-uuid
brew install homebrew/php/php70-xxtea
brew install homebrew/php/php70-yaf
brew install homebrew/php/php70-uopz
brew install homebrew/php/php70-pthreads
brew install homebrew/php/php70-msgpack
brew install homebrew/php/php70-gnupg
brew install homebrew/php/php70-ssh2
brew install homebrew/php/php70-mustache
brew install homebrew/php/php70-yac
brew install homebrew/php/php70-rdkafka

# PHP 7.1
source ~/Code/dotfiles/php/unlink.sh
brew link php71
brew install homebrew/php/php71-blitz
brew install homebrew/php/php71-ds
brew install homebrew/php/php71-ev
brew install homebrew/php/php71-geoip
brew install homebrew/php/php71-gmagick
brew install homebrew/php/php71-hprose
brew install homebrew/php/php71-libsodium
brew install homebrew/php/php71-lz4
brew install homebrew/php/php71-lzf
brew install homebrew/php/php71-mailparse
brew install homebrew/php/php71-maxminddb
brew install homebrew/php/php71-mecab
brew install homebrew/php/php71-mustache
brew install homebrew/php/php71-oauth
brew install homebrew/php/php71-ref
brew install homebrew/php/php71-solr
brew install homebrew/php/php71-stats
brew install homebrew/php/php71-uuid
brew install homebrew/php/php71-xxtea
brew install homebrew/php/php71-yaf
brew install homebrew/php/php71-ssh2
brew install homebrew/php/php71-yac
brew install homebrew/php/php71-rdkafka
brew install homebrew/php/php71-igbinary
brew install homebrew/php/php71-memcached
brew install homebrew/php/php71-yaml
brew install homebrew/php/php71-msgpack
brew install homebrew/php/php71-uv
brew install homebrew/php/php71-event

source ~/Code/dotfiles/php/unlink.sh
